#include "UILocalized.hpp"
#include <imgui.h>
#include <map>
#include <cassert>
#include <string>
#include "mods/FrameworkConfig.hpp"
using namespace std;

void UILocalized::add_localized_font(float m_font_size) {
    auto& fonts = ImGui::GetIO().Fonts;
    fonts->Clear();
    fonts->AddFontFromFileTTF("c:\\Windows\\Fonts\\msyh.ttc",m_font_size, nullptr, fonts->GetGlyphRangesChineseFull());
    fonts->Build();
    UILocalized::init_loc();
}

UILocalized::UILanguage UILocalized::get_ui_language_value() {
    return static_cast<UILanguage>(FrameworkConfig::get()->get_imgui_language_value());
}


static map<std::string, const char*> ZH_CN_Loc;
static map<std::string, const char*> CHT_Loc;
static map<std::string, const char*> ENG_Loc;
static map<std::string, const char*> m_current_Loc;

static UILocalized::UILanguage m_current_language;

void UILocalized::set_language() {
    if (m_current_language != UILocalized::get_ui_language_value()) {
        m_current_language = UILocalized::get_ui_language_value();
        switch (m_current_language) {
        case UILanguage::ENG:
            m_current_Loc = ENG_Loc;
            break;
        case UILanguage::ZH_CN:
            m_current_Loc = ZH_CN_Loc;
            break;
        case UILanguage::CHT:
            m_current_Loc = CHT_Loc;
            break;
        default:
            m_current_Loc = ZH_CN_Loc;
            break;
        }
    }
}

void add_zh_cn() {
    ZH_CN_Loc["Transparency"] = (const char*)u8"UI透明";
    ZH_CN_Loc["vrzwk"] = _S("汉化：vrzwk汉化组(vrzwk.com)");
    ZH_CN_Loc["Makes the UI transparent when not focused."] = _S("UI界面无焦点时透明。");
    ZH_CN_Loc["Input Passthrough"] = _S("输入直通");
    ZH_CN_Loc["Allows mouse and keyboard inputs to register to the game while the UI is focused."] = _S("当UI界面获取焦点时，允许鼠标和键盘输入到游戏。");
    ZH_CN_Loc["Show Advanced Options"] = _S("显示高级选项");
    ZH_CN_Loc["Show additional options for greater control over various settings."] = _S("显示其他选项以更好地进行各种设置。");
    ZH_CN_Loc["Reset to Default Settings"] = _S("恢复默认设置");
    ZH_CN_Loc["Keyboard Menu Key: Insert"] = _S("键盘菜单键：插入");
    ZH_CN_Loc["Gamepad L3 + R3: Toggle Menu"] = _S("手柄 L3+R3：切换菜单");
    ZH_CN_Loc["Gamepad RT: Shortcuts"] = _S("手柄 RT：快捷键");
    ZH_CN_Loc["Gamepad LB/RB: Change Sidebar Page"] = _S("手柄 LB/RB：更改边栏页面");
    ZH_CN_Loc["About"] = _S("关于");
    ZH_CN_Loc["Not bound"] = _S("未绑定");
    ZH_CN_Loc["Press any key..."] = _S("按下任意键...");
    ZH_CN_Loc["FrameworkConfig"] = _S("框架配置");
    ZH_CN_Loc["Main"] = _S("主页");
    ZH_CN_Loc["GUI/Themes"] = _S("视图/主题");
    ZH_CN_Loc["Menu Key"] = _S("菜单键");
    ZH_CN_Loc["Show Cursor Key"] = _S("显示光标键");
    ZH_CN_Loc["Remember Menu Open/Closed State"] = _S("记住菜单打开/关闭状态");
    ZH_CN_Loc["Enable L3 + R3 Toggle"] = _S("启用 L3 + R3 切换");
    ZH_CN_Loc["Always Show Cursor"] = _S("光标一直显示");
    ZH_CN_Loc["Select GUI Theme"] = _S("选择界面主题");
    ZH_CN_Loc["Font Size"] = _S("字体大小");
    ZH_CN_Loc["Attempt Unload Plugins"] = _S("尝试卸载插件");
    ZH_CN_Loc["Reload Plugins"] = _S("重新加载插件");
    ZH_CN_Loc["Loaded plugins:"] = _S("已加载插件:");
    ZH_CN_Loc["No plugins loaded."] = _S("未加载任何插件。");
    ZH_CN_Loc["Errors:"] = _S("错误:");
    ZH_CN_Loc["Warnings:"] = _S("警告:");
    ZH_CN_Loc["Author: praydog"] = _S("作者：praydog");
    ZH_CN_Loc["Licenses"] = _S("开源许可");
    ZH_CN_Loc["Runtime"] = _S("运行时");
    ZH_CN_Loc["Unreal"] = _S("虚幻引擎");
    ZH_CN_Loc["Input"] = _S("输入");
    ZH_CN_Loc["Camera"] = _S("相机");
    ZH_CN_Loc["Keybinds"] = _S("按键绑定");
    ZH_CN_Loc["WARNING: Hardware-accelerated GPU scheduling is enabled. This may cause the game to run slower."] = _S("警告：启用了硬件加速GPU调度。这可能会导致游戏运行速度变慢。");
    ZH_CN_Loc["Go into your Windows Graphics settings and disable \"Hardware-accelerated GPU scheduling\""] = _S("进入您的Windows图形设置并禁用“硬件加速GPU调度”");
    ZH_CN_Loc["Note: This is only necessary if you are experiencing performance issues."] = _S("注意：只有在遇到性能问题时才需要执行此操作。");
    ZH_CN_Loc["Unknown page selected"] = _S("选择了未知页面");
    ZH_CN_Loc["Runtime Information ("] = _S("运行时信息 (");
    ZH_CN_Loc["Desktop Spectator View"] = _S("桌面观众视图");
    ZH_CN_Loc["2D Screen Mode"] = _S("2D屏幕模式");
    ZH_CN_Loc["Render Resolution (per-eye): %d x %d"] = _S("渲染分辨率（单眼）: %d x %d");
    ZH_CN_Loc["Total Render Resolution: %d x %d"] = _S("总渲染分辨率: %d x %d");
    ZH_CN_Loc["Overlay Options"] = _S("覆盖选项");
    ZH_CN_Loc["Overlay Type"] = _S("覆盖类型");
    ZH_CN_Loc["UI Cylinder Angle"] = _S("UI柱面角度");
    ZH_CN_Loc["UI Offset"] = _S("UI偏移");
    ZH_CN_Loc["UI Distance"] = _S("UI距离");
    ZH_CN_Loc["UI Size"] = _S("UI大小");
    ZH_CN_Loc["UI Follows View"] = _S("UI跟随视图");
    ZH_CN_Loc["Framework Distance"] = _S("框架距离");
    ZH_CN_Loc["Framework Size"] = _S("框架大小");
    ZH_CN_Loc["Framework Follows View"] = _S("框架跟随视图");
    ZH_CN_Loc["Framework Wrist UI"] = _S("框架手腕UI");
    ZH_CN_Loc["Framework Mouse Emulation"] = _S("框架鼠标模拟");
    ZH_CN_Loc["Resolution can be changed in SteamVR"] = _S("可在SteamVR中更改分辨率");
    ZH_CN_Loc["Rendering Method"] = _S("渲染模式");
    ZH_CN_Loc["Synced Sequential Method"] = _S("同步顺序模式");
    ZH_CN_Loc["World Scale"] = _S("世界比例");
    ZH_CN_Loc["Depth Scale"] = _S("深度比例");
    ZH_CN_Loc["Disable HZBOcclusion"] = _S("禁用HZBOctication");
    ZH_CN_Loc["Disable Instance Culling"] = _S("禁用实例裁减");
    ZH_CN_Loc["Disable HDR Composition"] = _S("禁用HDR合成");
    ZH_CN_Loc["Disable Blur Widgets"] = _S("禁用模糊工具");
    ZH_CN_Loc["Continue holding down L3 + R3 to toggle aim method"] = _S("继续按住 L3+R3 切换瞄准方法");
    ZH_CN_Loc["AimMethod Notification"] = _S("瞄准方法通知");
    ZH_CN_Loc["RT Modifier Controls"] = _S("RT 修改器控件");
    ZH_CN_Loc["RT + Left Stick: Camera left/right/forward/back"] = _S("RT + 左摇杆：相机 左/右/前进/后退");
    ZH_CN_Loc["RT + Right Stick: Camera up/down"] = _S("RT + 右摇杆：相机 上/下");
    ZH_CN_Loc["Page: %d"] = _S("页: %d");
    ZH_CN_Loc["DPad Left: Previous page | DPad Right: Next page"] = _S("左DPad：上一页 | 右DPad：下一页");
    ZH_CN_Loc["RT + B: Save Camera 2"] = _S("RT + B：保存相机2");
    ZH_CN_Loc["RT + Y: Save Camera 1"] = _S("RT + Y：保存相机1");
    ZH_CN_Loc["RT + X: Save Camera 0"] = _S("RT + X：保存相机0");
    ZH_CN_Loc["RT + B: Load Camera 2"] = _S("RT + B：加载相机2");
    ZH_CN_Loc["RT + Y: Load Camera 1"] = _S("RT + Y：加载相机1");
    ZH_CN_Loc["RT + X: Load Camera 0"] = _S("RT + X：加载相机0");
    ZH_CN_Loc["RT + B: Reset camera offset"] = _S("RT + B：重置相机偏移");
    ZH_CN_Loc["RT + Y: Recenter view"] = _S("RT + Y：重置中心视图");
    ZH_CN_Loc["RT + X: Reset standing origin"] = _S("RT + X：重置站立原点");
    ZH_CN_Loc["Uncap Framerate"] = _S("取消帧率上限");
    ZH_CN_Loc["Enable GUI"] = _S("开启视图");
    ZH_CN_Loc["Enable Depth"] = _S("开启深度");
    ZH_CN_Loc["Load Blueprint Code"] = _S("加载蓝图代码");
    ZH_CN_Loc["Ghosting Fix"] = _S("修复鬼影");
    ZH_CN_Loc["Near Clip Plane"] = _S("近裁剪面");
    ZH_CN_Loc["Enable"] = _S("开启");
    ZH_CN_Loc["Value"] = _S("值");
    ZH_CN_Loc["Controller"] = _S("控制器");
    ZH_CN_Loc["VR Joystick Deadzone"] = _S("VR 摇杆死区");
    ZH_CN_Loc["DPad Shifting"] = _S("DPad 移位");
    ZH_CN_Loc["DPad Shifting Method"] = _S("DPad 移位方法");
    ZH_CN_Loc["Aim Method"] = _S("瞄准方法");
    ZH_CN_Loc["Experimental, may crash"] = _S("实验性的，可能会崩溃");
    ZH_CN_Loc["Some games may not work with this enabled."] = _S("启用此功能后，某些游戏可能无法运行。");
    ZH_CN_Loc["Type"] = _S("类型");
    ZH_CN_Loc["Speed"] = _S("速度");
    ZH_CN_Loc["Smoothing"] = _S("平滑");
    ZH_CN_Loc["Modify Player Control Rotation"] = _S("修改玩家转向控制");
    ZH_CN_Loc["Use Pawn Control Rotation"] = _S("使用Pawn控制旋转");
    ZH_CN_Loc["Multiplayer Support"] = _S("多人游戏支持");
    ZH_CN_Loc["Snap Turn"] = _S("急转");
    ZH_CN_Loc["Enabled"] = _S("已启用");
    ZH_CN_Loc["Set Snap Turn Rotation Angle in Degrees."] = _S("以度为单位设置捕捉旋转旋转角度。");
    ZH_CN_Loc["Angle"] = _S("角度");
    ZH_CN_Loc["Set Snap Turn Joystick Deadzone."] = _S("设置快速转动摇杆死区。");
    ZH_CN_Loc["Deadzone"] = _S("死区");
    ZH_CN_Loc["Movement Orientation"] = _S("运动方向");
    ZH_CN_Loc["Roomscale Movement"] = _S("室内运动");
    ZH_CN_Loc["Camera"] = _S("相机");
    ZH_CN_Loc["Save Camera 0"] = _S("保存相机0");
    ZH_CN_Loc["Save Camera 1"] = _S("保存相机1");
    ZH_CN_Loc["Save Camera 2"] = _S("保存相机2");
    ZH_CN_Loc["Load Camera 0"] = _S("加载相机0");
    ZH_CN_Loc["Load Camera 1"] = _S("加载相机1");
    ZH_CN_Loc["Load Camera 2"] = _S("加载相机2");
    ZH_CN_Loc["Decoupled Pitch"] = _S("场地解耦");
    ZH_CN_Loc["Auto Adjust UI"] = _S("自动调整UI");
    ZH_CN_Loc["Playspace Keys"] = _S("游戏空间按键");
    ZH_CN_Loc["Recenter View Key"] = _S("重新居中视图键");
    ZH_CN_Loc["Set Standing Origin Key"] = _S("重置视图键");
    ZH_CN_Loc["Camera Keys"] = _S("相机按键");
    ZH_CN_Loc["Load Camera 0 Key"] = _S("加载相机0按键");
    ZH_CN_Loc["Load Camera 1 Key"] = _S("加载相机1按键");
    ZH_CN_Loc["Load Camera 2 Key"] = _S("加载相机2按键");
    ZH_CN_Loc["Overlay/Runtime Keys"] = _S("叠加/运行时按键");
    ZH_CN_Loc["Toggle 2D Screen Mode Key"] = _S("切换2D屏幕模式键");
    ZH_CN_Loc["Disable VR Key"] = _S("禁用VR键");
    ZH_CN_Loc["Compatibility Options"] = _S("兼容性选项");
    ZH_CN_Loc["Skip UObjectArray Init"] = _S("跳过UObjectArray初始化");
    ZH_CN_Loc["Skip PostInitProperties"] = _S("跳过PostInitProperties");
    ZH_CN_Loc["SceneView Compatibility Mode"] = _S("场景视图兼容模式");
    ZH_CN_Loc["Extreme Compatibility Mode"] = _S("极端兼容模式");
    ZH_CN_Loc["Splitscreen Compatibility"] = _S("分屏兼容性");
    ZH_CN_Loc["Index"] = _S("序号");
    ZH_CN_Loc["Sync Mode"] = _S("同步模式");
    ZH_CN_Loc["Early\0Late\0Very Late\0"] = _S("早\0晚\0非常晚\0");
    ZH_CN_Loc["Right Bounds"] = _S("右侧边界");
    ZH_CN_Loc["Left Bounds"] = _S("左侧边界");
    ZH_CN_Loc["Disable Projection Matrix Override"] = _S("禁用投影矩阵覆盖");
    ZH_CN_Loc["Disable View Matrix Override"] = _S("禁用视图矩阵覆盖");
    ZH_CN_Loc["Disable Backbuffer Size Override"] = _S("禁用备份缓冲区大小覆盖");
    ZH_CN_Loc["Disable VR Overlay"] = _S("禁用VR覆盖");
    ZH_CN_Loc["Disable VR Entirely"] = _S("完全禁用VR");
    ZH_CN_Loc["Stereo Emulation Mode"] = _S("立体声仿真模式");
    ZH_CN_Loc["Wait for Present"] = _S("等待呈现");
    ZH_CN_Loc["Controllers allowed"] = _S("允许的控制器");
    ZH_CN_Loc["Controller test mode"] = _S("控制器测试模式");
    ZH_CN_Loc["Prediction Scale"] = _S("预测标尺");
    ZH_CN_Loc["Raw Left"] = _S("左");
    ZH_CN_Loc["Raw Right"] = _S("右");
    ZH_CN_Loc["Left Stick"] = _S("左摇杆");
    ZH_CN_Loc["Right Stick"] = _S("右摇杆");
    ZH_CN_Loc["Hardware scheduling: %s"] = _S("硬件调度: %s");
    ZH_CN_Loc["Disabled"] = _S("已禁用");
    ZH_CN_Loc["Loading..."] = _S("加载中...");
    ZH_CN_Loc["%s not loaded: %s not found"] = _S("%s未被加载: 未找到%s");
    ZH_CN_Loc["Please select %s from the loader if you want to use %s"] = _S("请从加载器中选择%s，如果你想使用%s的话");
    ZH_CN_Loc["%s not loaded: %s"] = _S("%s未被加载: %s");
    ZH_CN_Loc["%s not loaded: Unknown error"] = _S("%s未被加载: 未知错误");
    ZH_CN_Loc["No runtime loaded."] = _S("未加载任何运行时。");
    ZH_CN_Loc["Attempt to reinitialize"] = _S("尝试重新初始化");
    ZH_CN_Loc["Set Standing Height"] = _S("设置站立高度");
    ZH_CN_Loc["Set Standing Origin"] = _S("设置站立原点");
    ZH_CN_Loc["Recenter View"] = _S("重新居中视图");
    ZH_CN_Loc["Reinitialize Runtime"] = _S("重新初始化运行时");
    ZH_CN_Loc["Console/CVars"] = _S("控制台/CVars");
    ZH_CN_Loc["Compatibility"] = _S("兼容性");
    ZH_CN_Loc["Debug"] = _S("调试");
    ZH_CN_Loc["Note: Any changes here will be frozen."] = _S("注意：此处的任何更改都将被冻结。");
    ZH_CN_Loc["Frozen CVars: %i"] = _S("冻结的CVars: %i");
    ZH_CN_Loc["Display Console"] = _S("显示控制台");
    ZH_CN_Loc["Spawn Native Console"] = _S("生成本地控制台");
    ZH_CN_Loc["Dump All CVars"] = _S("转储所有CVars");
    ZH_CN_Loc["Clear Frozen CVars"] = _S("清除冻结的CVars");
    ZH_CN_Loc["Failed to get FConsoleManager."] = _S("无法获取FConsoleManager。");
    ZH_CN_Loc["Note: This is a homebrew console. It is not the same as the in-game console."] = _S("注意: 这是一个自制的控制台，与游戏中的控制台不同。");
    ZH_CN_Loc["Command"] = _S("命令");
    ZH_CN_Loc["Description"] = _S("描述");
    ZH_CN_Loc["Failed to find cvar: %s"] = _S("未能找到cvar：%s");
    ZH_CN_Loc["Unimplemented cvar type: %s"] = _S("未实现的cvar类型：%s");
    ZH_CN_Loc["Failed to read cvar: %s"] = _S("读取cvar失败: %s");
    ZH_CN_Loc["Failed to find cvar data: %s"] = _S("查找cvar数据失败: %s");
    ZH_CN_Loc["Failed to read cvar data: %s"] = _S("读取cvar数据失败: %s");
    ZH_CN_Loc["Stereo Hook Options"] = _S("立体钩子选项");
    ZH_CN_Loc["Asynchronous Code Scanning"] = _S("异步代码扫描");
    ZH_CN_Loc["Recreate Textures on Reset"] = _S("重置时重新创建纹理");
    ZH_CN_Loc["Frame Delay Compensation"] = _S("帧延迟补偿");
    ZH_CN_Loc["Config"] = _S("配置");
    ZH_CN_Loc["Developer"] = _S("开发者");
    ZH_CN_Loc["PluginLoader"] = _S("插件加载器");
    ZH_CN_Loc["Waiting for UObjectBase to be hooked..."] = _S("等待UObjectBase被挂钩...");
    ZH_CN_Loc["Reload Persistent States"] = _S("重新加载持久状态");
    ZH_CN_Loc["Destroy Persistent States"] = _S("清除持久状态");
    ZH_CN_Loc["Enabled at Startup"] = _S("在启动时启用");
    ZH_CN_Loc["Enable Attach Lerp"] = _S("启用附加Lerp");
    ZH_CN_Loc["Dump SDK"] = _S("转储SDK");
    ZH_CN_Loc["Attached Components"] = _S("附加组件");
    ZH_CN_Loc["Detach all"] = _S("全部分离");
    ZH_CN_Loc["Attached Camera Object"] = _S("附加相机对象");
    ZH_CN_Loc["Detach Camera"] = _S("分离相机");
    ZH_CN_Loc["Spawn Overlapper"] = _S("生成叠加器");
    ZH_CN_Loc["Overlapped Objects"] = _S("叠加的对象");
    ZH_CN_Loc["Destroy Overlapper"] = _S("清除叠加器");
    ZH_CN_Loc["Attach all"] = _S("附加全部");
    ZH_CN_Loc["Objects: %zu (%zu actual)"] = _S("对象: %zu (真实 %zu)");
    ZH_CN_Loc["Recent Objects"] = _S("最近使用的对象");
    ZH_CN_Loc["Common Objects"] = _S("公共对象");
    ZH_CN_Loc["PlayerController"] = _S("玩家控制器");
    ZH_CN_Loc["Player Controller"] = _S("玩家控制器");
    ZH_CN_Loc["No player controller"] = _S("无玩家控制器");
    ZH_CN_Loc["Acknowledged Pawn"] = _S("已确认生成");
    ZH_CN_Loc["No pawn"] = _S("未生成");
    ZH_CN_Loc["Camera Manager"] = _S("相机管理器");
    ZH_CN_Loc["No camera manager"] = _S("无相机管理器");
    ZH_CN_Loc["World"] = _S("世界");
    ZH_CN_Loc["No world"] = _S("无世界");
    ZH_CN_Loc["Objects by class"] = _S("按类排列对象");
    ZH_CN_Loc["Filter"] = _S("过滤");
    ZH_CN_Loc["Add Component Permanently"] = _S("永久添加组件");
    ZH_CN_Loc["Copy Name"] = _S("复制名称");
    ZH_CN_Loc["Copy Address"] = _S("复制地址");
    ZH_CN_Loc["Set to Screen Space"] = _S("设置为屏幕空间");
    ZH_CN_Loc["Detach"] = _S("分离");
    ZH_CN_Loc["Adjust"] = _S("调整");
    ZH_CN_Loc["Permanent Change"] = _S("永久变更");
    ZH_CN_Loc["Save state"] = _S("保存状态");
    ZH_CN_Loc["Can't save, did not start from a valid base or none of the allowed bases can reach this component"] = _S("无法保存，没有从有效的基类开始的，或者允许的基类不能达到此组件");
    ZH_CN_Loc["Attach left"] = _S("附加左侧");
    ZH_CN_Loc["Attach right"] = _S("附加右侧");
    ZH_CN_Loc["Attach Camera to"] = _S("附加相机到");
    ZH_CN_Loc["Attach Camera to (Relative)"] = _S("附加相机到(相对的)");
    ZH_CN_Loc["Camera Offset"] = _S("相机偏移");
    ZH_CN_Loc["Visible"] = _S("显示");
    ZH_CN_Loc["Save Visibility State"] = _S("保存隐藏显示状态");
    ZH_CN_Loc["Apply to all actors"] = _S("适用于所有参与者");
    ZH_CN_Loc["Add Component"] = _S("添加组件");
    ZH_CN_Loc["Components"] = _S("组件");
    ZH_CN_Loc["Call"] = _S("调用");
    ZH_CN_Loc["Disable"] = _S("关闭");
    ZH_CN_Loc["Can't save, did not start from a valid base"] = _S("无法保存，没有从有效的基类开始");
    ZH_CN_Loc["Empty array"] = _S("空数组");
    ZH_CN_Loc["Failed to get inner property"] = _S("无法获取内部属性");
    ZH_CN_Loc["Failed to get inner property class"] = _S("无法获取内部属性类");
    ZH_CN_Loc["Array of %s (unsupported)"] = _S("%s数组(不支持)");
    ZH_CN_Loc["Inheritance"] = _S("继承");
    ZH_CN_Loc["Functions"] = _S("方法");
    ZH_CN_Loc["Properties"] = _S("属性");
    ZH_CN_Loc["UObjectHook is disabled"] = _S("UObjectHook已禁用");
    ZH_CN_Loc["Re-enable"] = _S("重新启用");
    ZH_CN_Loc["RotationOffset"] = _S("旋转偏移");
    ZH_CN_Loc["PositionOffset"] = _S("位置偏移");
    ZH_CN_Loc["L3 + R3 Long Press Menu Toggle"] = _S("L3 + R3 长按菜单切换");
    ZH_CN_Loc["Debug Stats"] = _S("调试信息");
    ZH_CN_Loc["Select GUI Language"] = _S("选择界面语言");
}


void add_cht() {
    CHT_Loc["Transparency"] = (const char*)u8"UI透明";
    CHT_Loc["vrzwk"] = _S("漢化：vrzwk漢化組(vrzwk.com)");
    CHT_Loc["Makes the UI transparent when not focused."] = _S("UI界面無焦點時透明。");
    CHT_Loc["Input Passthrough"] = _S("輸入直通");
    CHT_Loc["Allows mouse and keyboard inputs to register to the game while the UI is focused."] = _S("當UI界面獲取焦點時，允許鼠標和鍵盤輸入到遊戲。");
    CHT_Loc["Show Advanced Options"] = _S("顯示高級選項");
    CHT_Loc["Show additional options for greater control over various settings."] = _S("顯示其他選項以更好地進行各種設置。");
    CHT_Loc["Reset to Default Settings"] = _S("恢複默認設置");
    CHT_Loc["Keyboard Menu Key: Insert"] = _S("鍵盤菜單鍵：插入");
    CHT_Loc["Gamepad L3 + R3: Toggle Menu"] = _S("手柄 L3+R3：切換菜單");
    CHT_Loc["Gamepad RT: Shortcuts"] = _S("手柄 RT：快捷鍵");
    CHT_Loc["Gamepad LB/RB: Change Sidebar Page"] = _S("手柄 LB/RB：更改邊欄頁面");
    CHT_Loc["About"] = _S("關于");
    CHT_Loc["Not bound"] = _S("未綁定");
    CHT_Loc["Press any key..."] = _S("按下任意鍵...");
    CHT_Loc["FrameworkConfig"] = _S("框架配置");
    CHT_Loc["Main"] = _S("主頁");
    CHT_Loc["GUI/Themes"] = _S("視圖/主題");
    CHT_Loc["Menu Key"] = _S("菜單鍵");
    CHT_Loc["Show Cursor Key"] = _S("顯示光標鍵");
    CHT_Loc["Remember Menu Open/Closed State"] = _S("記住菜單打開/關閉狀態");
    CHT_Loc["Enable L3 + R3 Toggle"] = _S("啓用 L3 + R3 切換");
    CHT_Loc["Always Show Cursor"] = _S("光標壹直顯示");
    CHT_Loc["Select GUI Theme"] = _S("選擇界面主題");
    CHT_Loc["Font Size"] = _S("字體大小");
    CHT_Loc["Attempt Unload Plugins"] = _S("嘗試卸載插件");
    CHT_Loc["Reload Plugins"] = _S("重新加載插件");
    CHT_Loc["Loaded plugins:"] = _S("已加載插件:");
    CHT_Loc["No plugins loaded."] = _S("未加載任何插件。");
    CHT_Loc["Errors:"] = _S("錯誤:");
    CHT_Loc["Warnings:"] = _S("警告:");
    CHT_Loc["Author: praydog"] = _S("作者：praydog");
    CHT_Loc["Licenses"] = _S("開源許可");
    CHT_Loc["Runtime"] = _S("運行時");
    CHT_Loc["Unreal"] = _S("虛幻引擎");
    CHT_Loc["Input"] = _S("輸入");
    CHT_Loc["Camera"] = _S("相機");
    CHT_Loc["Keybinds"] = _S("按鍵綁定");
    CHT_Loc["WARNING: Hardware-accelerated GPU scheduling is enabled. This may cause the game to run slower."] = _S("警告：啓用了硬件加速GPU調度。這可能會導致遊戲運行速度變慢。");
    CHT_Loc["Go into your Windows Graphics settings and disable \"Hardware-accelerated GPU scheduling\""] = _S("進入您的Windows圖形設置並禁用“硬件加速GPU調度”");
    CHT_Loc["Note: This is only necessary if you are experiencing performance issues."] = _S("注意：只有在遇到性能問題時才需要執行此操作。");
    CHT_Loc["Unknown page selected"] = _S("選擇了未知頁面");
    CHT_Loc["Runtime Information ("] = _S("運行時信息 (");
    CHT_Loc["Desktop Spectator View"] = _S("桌面觀衆視圖");
    CHT_Loc["2D Screen Mode"] = _S("2D屏幕模式");
    CHT_Loc["Render Resolution (per-eye): %d x %d"] = _S("渲染分辨率（單眼）: %d x %d");
    CHT_Loc["Total Render Resolution: %d x %d"] = _S("總渲染分辨率: %d x %d");
    CHT_Loc["Overlay Options"] = _S("覆蓋選項");
    CHT_Loc["Overlay Type"] = _S("覆蓋類型");
    CHT_Loc["UI Cylinder Angle"] = _S("UI柱面角度");
    CHT_Loc["UI Offset"] = _S("UI偏移");
    CHT_Loc["UI Distance"] = _S("UI距離");
    CHT_Loc["UI Size"] = _S("UI大小");
    CHT_Loc["UI Follows View"] = _S("UI跟隨視圖");
    CHT_Loc["Framework Distance"] = _S("框架距離");
    CHT_Loc["Framework Size"] = _S("框架大小");
    CHT_Loc["Framework Follows View"] = _S("框架跟隨視圖");
    CHT_Loc["Framework Wrist UI"] = _S("框架手腕UI");
    CHT_Loc["Framework Mouse Emulation"] = _S("框架鼠標模擬");
    CHT_Loc["Resolution can be changed in SteamVR"] = _S("可在SteamVR中更改分辨率");
    CHT_Loc["Rendering Method"] = _S("渲染模式");
    CHT_Loc["Synced Sequential Method"] = _S("同步順序模式");
    CHT_Loc["World Scale"] = _S("世界比例");
    CHT_Loc["Depth Scale"] = _S("深度比例");
    CHT_Loc["Disable HZBOcclusion"] = _S("禁用HZBOctication");
    CHT_Loc["Disable Instance Culling"] = _S("禁用實例裁減");
    CHT_Loc["Disable HDR Composition"] = _S("禁用HDR合成");
    CHT_Loc["Disable Blur Widgets"] = _S("禁用模糊工具");
    CHT_Loc["Continue holding down L3 + R3 to toggle aim method"] = _S("繼續按住 L3+R3 切換瞄准方法");
    CHT_Loc["AimMethod Notification"] = _S("瞄准方法通知");
    CHT_Loc["RT Modifier Controls"] = _S("RT 修改器控件");
    CHT_Loc["RT + Left Stick: Camera left/right/forward/back"] = _S("RT + 左搖杆：相機 左/右/前進/後退");
    CHT_Loc["RT + Right Stick: Camera up/down"] = _S("RT + 右搖杆：相機 上/下");
    CHT_Loc["Page: %d"] = _S("頁: %d");
    CHT_Loc["DPad Left: Previous page | DPad Right: Next page"] = _S("左DPad：上壹頁 | 右DPad：下壹頁");
    CHT_Loc["RT + B: Save Camera 2"] = _S("RT + B：保存相機2");
    CHT_Loc["RT + Y: Save Camera 1"] = _S("RT + Y：保存相機1");
    CHT_Loc["RT + X: Save Camera 0"] = _S("RT + X：保存相機0");
    CHT_Loc["RT + B: Load Camera 2"] = _S("RT + B：加載相機2");
    CHT_Loc["RT + Y: Load Camera 1"] = _S("RT + Y：加載相機1");
    CHT_Loc["RT + X: Load Camera 0"] = _S("RT + X：加載相機0");
    CHT_Loc["RT + B: Reset camera offset"] = _S("RT + B：重置相機偏移");
    CHT_Loc["RT + Y: Recenter view"] = _S("RT + Y：重置中心視圖");
    CHT_Loc["RT + X: Reset standing origin"] = _S("RT + X：重置站立原點");
    CHT_Loc["Uncap Framerate"] = _S("取消幀率上限");
    CHT_Loc["Enable GUI"] = _S("開啓視圖");
    CHT_Loc["Enable Depth"] = _S("開啓深度");
    CHT_Loc["Load Blueprint Code"] = _S("加載藍圖代碼");
    CHT_Loc["Ghosting Fix"] = _S("修複鬼影");
    CHT_Loc["Near Clip Plane"] = _S("近裁剪面");
    CHT_Loc["Enable"] = _S("開啓");
    CHT_Loc["Value"] = _S("值");
    CHT_Loc["Controller"] = _S("控制器");
    CHT_Loc["VR Joystick Deadzone"] = _S("VR 搖杆死區");
    CHT_Loc["DPad Shifting"] = _S("DPad 移位");
    CHT_Loc["DPad Shifting Method"] = _S("DPad 移位方法");
    CHT_Loc["Aim Method"] = _S("瞄准方法");
    CHT_Loc["Experimental, may crash"] = _S("實驗性的，可能會崩潰");
    CHT_Loc["Some games may not work with this enabled."] = _S("啓用此功能後，某些遊戲可能無法運行。");
    CHT_Loc["Type"] = _S("類型");
    CHT_Loc["Speed"] = _S("速度");
    CHT_Loc["Smoothing"] = _S("平滑");
    CHT_Loc["Modify Player Control Rotation"] = _S("修改玩家轉向控制");
    CHT_Loc["Use Pawn Control Rotation"] = _S("使用Pawn控制旋轉");
    CHT_Loc["Multiplayer Support"] = _S("多人遊戲支持");
    CHT_Loc["Snap Turn"] = _S("急轉");
    CHT_Loc["Enabled"] = _S("已啓用");
    CHT_Loc["Set Snap Turn Rotation Angle in Degrees."] = _S("以度爲單位設置捕捉旋轉旋轉角度。");
    CHT_Loc["Angle"] = _S("角度");
    CHT_Loc["Set Snap Turn Joystick Deadzone."] = _S("設置快速轉動搖杆死區。");
    CHT_Loc["Deadzone"] = _S("死區");
    CHT_Loc["Movement Orientation"] = _S("運動方向");
    CHT_Loc["Roomscale Movement"] = _S("室內運動");
    CHT_Loc["Camera"] = _S("相機");
    CHT_Loc["Save Camera 0"] = _S("保存相機0");
    CHT_Loc["Save Camera 1"] = _S("保存相機1");
    CHT_Loc["Save Camera 2"] = _S("保存相機2");
    CHT_Loc["Load Camera 0"] = _S("加載相機0");
    CHT_Loc["Load Camera 1"] = _S("加載相機1");
    CHT_Loc["Load Camera 2"] = _S("加載相機2");
    CHT_Loc["Decoupled Pitch"] = _S("場地解藕");
    CHT_Loc["Auto Adjust UI"] = _S("自動調整UI");
    CHT_Loc["Playspace Keys"] = _S("遊戲空間按鍵");
    CHT_Loc["Recenter View Key"] = _S("重新居中視圖鍵");
    CHT_Loc["Set Standing Origin Key"] = _S("重置視圖鍵");
    CHT_Loc["Camera Keys"] = _S("相機按鍵");
    CHT_Loc["Load Camera 0 Key"] = _S("加載相機0按鍵");
    CHT_Loc["Load Camera 1 Key"] = _S("加載相機1按鍵");
    CHT_Loc["Load Camera 2 Key"] = _S("加載相機2按鍵");
    CHT_Loc["Overlay/Runtime Keys"] = _S("疊加/運行時按鍵");
    CHT_Loc["Toggle 2D Screen Mode Key"] = _S("切換2D屏幕模式鍵");
    CHT_Loc["Disable VR Key"] = _S("禁用VR鍵");
    CHT_Loc["Compatibility Options"] = _S("兼容性選項");
    CHT_Loc["Skip UObjectArray Init"] = _S("跳過UObjectArray初始化");
    CHT_Loc["Skip PostInitProperties"] = _S("跳過PostInitProperties");
    CHT_Loc["SceneView Compatibility Mode"] = _S("場景視圖兼容模式");
    CHT_Loc["Extreme Compatibility Mode"] = _S("極端兼容模式");
    CHT_Loc["Splitscreen Compatibility"] = _S("分屏兼容性");
    CHT_Loc["Index"] = _S("序號");
    CHT_Loc["Sync Mode"] = _S("同步模式");
    CHT_Loc["Early\0Late\0Very Late\0"] = _S("早\0晚\0非常晚\0");
    CHT_Loc["Right Bounds"] = _S("右側邊界");
    CHT_Loc["Left Bounds"] = _S("左側邊界");
    CHT_Loc["Disable Projection Matrix Override"] = _S("禁用投影矩陣覆蓋");
    CHT_Loc["Disable View Matrix Override"] = _S("禁用視圖矩陣覆蓋");
    CHT_Loc["Disable Backbuffer Size Override"] = _S("禁用備份緩沖區大小覆蓋");
    CHT_Loc["Disable VR Overlay"] = _S("禁用VR覆蓋");
    CHT_Loc["Disable VR Entirely"] = _S("完全禁用VR");
    CHT_Loc["Stereo Emulation Mode"] = _S("立體聲仿真模式");
    CHT_Loc["Wait for Present"] = _S("等待呈現");
    CHT_Loc["Controllers allowed"] = _S("允許的控制器");
    CHT_Loc["Controller test mode"] = _S("控制器測試模式");
    CHT_Loc["Prediction Scale"] = _S("預測標尺");
    CHT_Loc["Raw Left"] = _S("左");
    CHT_Loc["Raw Right"] = _S("右");
    CHT_Loc["Left Stick"] = _S("左搖杆");
    CHT_Loc["Right Stick"] = _S("右搖杆");
    CHT_Loc["Hardware scheduling: %s"] = _S("硬件調度: %s");
    CHT_Loc["Disabled"] = _S("已禁用");
    CHT_Loc["Loading..."] = _S("加載中...");
    CHT_Loc["%s not loaded: %s not found"] = _S("%s未被加載: 未找到%s");
    CHT_Loc["Please select %s from the loader if you want to use %s"] = _S("請從加載器中選擇%s，如果妳想使用%s的話");
    CHT_Loc["%s not loaded: %s"] = _S("%s未被加載: %s");
    CHT_Loc["%s not loaded: Unknown error"] = _S("%s未被加載: 未知錯誤");
    CHT_Loc["No runtime loaded."] = _S("未加載任何運行時。");
    CHT_Loc["Attempt to reinitialize"] = _S("嘗試重新初始化");
    CHT_Loc["Set Standing Height"] = _S("設置站立高度");
    CHT_Loc["Set Standing Origin"] = _S("設置站立原點");
    CHT_Loc["Recenter View"] = _S("重新居中視圖");
    CHT_Loc["Reinitialize Runtime"] = _S("重新初始化運行時");
    CHT_Loc["Console/CVars"] = _S("控制台/CVars");
    CHT_Loc["Compatibility"] = _S("兼容性");
    CHT_Loc["Debug"] = _S("調試");
    CHT_Loc["Note: Any changes here will be frozen."] = _S("注意：此處的任何更改都將被凍結。");
    CHT_Loc["Frozen CVars: %i"] = _S("凍結的CVars: %i");
    CHT_Loc["Display Console"] = _S("顯示控制台");
    CHT_Loc["Spawn Native Console"] = _S("生成本地控制台");
    CHT_Loc["Dump All CVars"] = _S("轉儲所有CVars");
    CHT_Loc["Clear Frozen CVars"] = _S("清除凍結的CVars");
    CHT_Loc["Failed to get FConsoleManager."] = _S("無法獲取FConsoleManager。");
    CHT_Loc["Note: This is a homebrew console. It is not the same as the in-game console."] = _S("注意: 這是壹個自制的控制台，與遊戲中的控制台不同。");
    CHT_Loc["Command"] = _S("命令");
    CHT_Loc["Description"] = _S("描述");
    CHT_Loc["Failed to find cvar: %s"] = _S("未能找到cvar：%s");
    CHT_Loc["Unimplemented cvar type: %s"] = _S("未實現的cvar類型：%s");
    CHT_Loc["Failed to read cvar: %s"] = _S("讀取cvar失敗: %s");
    CHT_Loc["Failed to find cvar data: %s"] = _S("查找cvar數據失敗: %s");
    CHT_Loc["Failed to read cvar data: %s"] = _S("讀取cvar數據失敗: %s");
    CHT_Loc["Stereo Hook Options"] = _S("立體鈎子選項");
    CHT_Loc["Asynchronous Code Scanning"] = _S("異步代碼掃描");
    CHT_Loc["Recreate Textures on Reset"] = _S("重置時重新創建紋理");
    CHT_Loc["Frame Delay Compensation"] = _S("幀延遲補償");
    CHT_Loc["Config"] = _S("配置");
    CHT_Loc["Developer"] = _S("開發者");
    CHT_Loc["PluginLoader"] = _S("插件加載器");
    CHT_Loc["Waiting for UObjectBase to be hooked..."] = _S("等待UObjectBase被挂鈎...");
    CHT_Loc["Reload Persistent States"] = _S("重新加載持久狀態");
    CHT_Loc["Destroy Persistent States"] = _S("清除持久狀態");
    CHT_Loc["Enabled at Startup"] = _S("在啓動時啓用");
    CHT_Loc["Enable Attach Lerp"] = _S("啓用附加Lerp");
    CHT_Loc["Dump SDK"] = _S("轉儲SDK");
    CHT_Loc["Attached Components"] = _S("附加組件");
    CHT_Loc["Detach all"] = _S("全部分離");
    CHT_Loc["Attached Camera Object"] = _S("附加相機對象");
    CHT_Loc["Detach Camera"] = _S("分離相機");
    CHT_Loc["Spawn Overlapper"] = _S("生成疊加器");
    CHT_Loc["Overlapped Objects"] = _S("疊加的對象");
    CHT_Loc["Destroy Overlapper"] = _S("清除疊加器");
    CHT_Loc["Attach all"] = _S("附加全部");
    CHT_Loc["Objects: %zu (%zu actual)"] = _S("對象: %zu (真實 %zu)");
    CHT_Loc["Recent Objects"] = _S("最近使用的對象");
    CHT_Loc["Common Objects"] = _S("公共對象");
    CHT_Loc["PlayerController"] = _S("玩家控制器");
    CHT_Loc["Player Controller"] = _S("玩家控制器");
    CHT_Loc["No player controller"] = _S("無玩家控制器");
    CHT_Loc["Acknowledged Pawn"] = _S("已確認生成");
    CHT_Loc["No pawn"] = _S("未生成");
    CHT_Loc["Camera Manager"] = _S("相機管理器");
    CHT_Loc["No camera manager"] = _S("無相機管理器");
    CHT_Loc["World"] = _S("世界");
    CHT_Loc["No world"] = _S("無世界");
    CHT_Loc["Objects by class"] = _S("按類排列對象");
    CHT_Loc["Filter"] = _S("過濾");
    CHT_Loc["Add Component Permanently"] = _S("永久添加組件");
    CHT_Loc["Copy Name"] = _S("複制名稱");
    CHT_Loc["Copy Address"] = _S("複制地址");
    CHT_Loc["Set to Screen Space"] = _S("設置爲屏幕空間");
    CHT_Loc["Detach"] = _S("分離");
    CHT_Loc["Adjust"] = _S("調整");
    CHT_Loc["Permanent Change"] = _S("永久變更");
    CHT_Loc["Save state"] = _S("保存狀態");
    CHT_Loc["Can't save, did not start from a valid base or none of the allowed bases can reach this component"] = _S("無法保存，沒有從有效的基類開始的，或者允許的基類不能達到此組件");
    CHT_Loc["Attach left"] = _S("附加左側");
    CHT_Loc["Attach right"] = _S("附加右側");
    CHT_Loc["Attach Camera to"] = _S("附加相機到");
    CHT_Loc["Attach Camera to (Relative)"] = _S("附加相機到(相對的)");
    CHT_Loc["Camera Offset"] = _S("相機偏移");
    CHT_Loc["Visible"] = _S("顯示");
    CHT_Loc["Save Visibility State"] = _S("保存隱藏顯示狀態");
    CHT_Loc["Apply to all actors"] = _S("適用于所有參與者");
    CHT_Loc["Add Component"] = _S("添加組件");
    CHT_Loc["Components"] = _S("組件");
    CHT_Loc["Call"] = _S("調用");
    CHT_Loc["Disable"] = _S("關閉");
    CHT_Loc["Can't save, did not start from a valid base"] = _S("無法保存，沒有從有效的基類開始");
    CHT_Loc["Empty array"] = _S("空數組");
    CHT_Loc["Failed to get inner property"] = _S("無法獲取內部屬性");
    CHT_Loc["Failed to get inner property class"] = _S("無法獲取內部屬性類");
    CHT_Loc["Array of %s (unsupported)"] = _S("%s數組(不支持)");
    CHT_Loc["Inheritance"] = _S("繼承");
    CHT_Loc["Functions"] = _S("方法");
    CHT_Loc["Properties"] = _S("屬性");
    CHT_Loc["UObjectHook is disabled"] = _S("UObjectHook已禁用");
    CHT_Loc["Re-enable"] = _S("重新啓用");
    CHT_Loc["RotationOffset"] = _S("旋轉偏移");
    CHT_Loc["PositionOffset"] = _S("位置偏移");
    CHT_Loc["L3 + R3 Long Press Menu Toggle"] = _S("L3 + R3 長按菜單切換");
    CHT_Loc["Debug Stats"] = _S("調試信息");
    CHT_Loc["Select GUI Language"] = _S("選擇界面語言");
}

void UILocalized::init_loc() {
    ImGui::imgui_localized_func_ptr = UILocalized::get_localized_text;
    m_current_Loc = ZH_CN_Loc;
    add_zh_cn();
    add_cht();
}



const char* UILocalized::get_localized_text(const char* text) {
    if (m_current_Loc.find(text) != m_current_Loc.end()) {
        return m_current_Loc[text];
    } 
    return text;
}


